language: go
go:
- master
sudo: required
services:
- docker
if: branch IN (master, develop)
script:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker build -t drivereu/large-file-service:$TRAVIS_BRANCH-latest .
- if [ $TRAVIS_BRANCH == "master" ]; then docker tag drivereu/large-file-service:$TRAVIS_BRANCH-latest
  drivereu/large-file-service:latest; fi
- if [ ! -z $TRAVIS_TAG ]; then docker tag drivereu/large-file-service:$TRAVIS_BRANCH-latest
  drivereu/large-file-service:$TRAVIS_TAG; fi
- docker push drivereu/large-file-service
env:
  global:
  - secure: m9FjNZcrDkkRCKPDeMUrv1vwEpN1LAzkbQqQTIuvKn+zGAqJlmSXlVi+T1gloEIeWw7PjJCqX/gYNj4Iggd/JrHYtFoOq4UG39Q1PM0nTe+mUp+t2Hpvu/Xac7d03vqb7VnMTfM3q5PqlHEOoJMoV/lxiWrXKOjgoFdR86P40lrb8n00B5tE+eyPhEfrXJ8JdxSrOgESBhcqbDqlVG/CJOQFfFLqTiShhWJoo7RfpxisDx1rtnv5jS9SDMD9hD0Uy4oU4wiHqZyCBDGuqGIIOjmVsDL5yeFeR9NjSka+mP0e1sZZisHjiymwibs8BugrGgfovUsW+mtnLTBufgwcVUp01YMEhCkGHfWCKyzDzDLRXqdjAtl5sygBeL0zGdD17PWhJEmhEvX4cj24o3PvfwL8BcYErG0aLhWvYBHOOMuBEzVJTner6FmbgZtYNf0QhvzgkJpb9EEPrXatVmcpGk+UvsVeGoeAiRzz5kBeq2e1sOkouimaStQuaN6J55c/Y9QX3NTEgtEBuz0madhDnwMA9AWuHiYFwXHGRQ5LmB2mUE8AIccvS6ijetl4Eh34HaeXUENLwtY5nra4nK4fxcp0mTNaX8dWSgvzuczgV3UuCCRjpuQHHLsLUA6yAPEmMXrGwZR0jUitLIdQfyYbSm0/krfWIPbMvEn2GyQxGJw=
  - secure: epOtePYJ7EinvOlPPkXaY/mEY4de8PGh7PRFPLDWKGLaVsXpRP3tAb/M1tbOd/V+uvCa2EYFlOWdn3quSkaHFeQH87KQNLRsyVr/HSW/OMlAYYaju86WbvWrCg+9KZrjevQGrDIjqaC5w6LRHfugSOAWJuP9lngIhY1aLDAMEYSEGgkVyr1DjJZEs0X4qrnpDGxvHHTv7mswnX6/njGTPSSTUDrX3Nh//rn/hltsw0WjhtOsIMCTHYuDI3jpL8m6Zeag/2Su1ZDoitbSMYLa3FMNhmThIMZt58jPWhCRAiq98XK8QGqfwdxYSobAJvpeFaZyWccvofi6GocQksHRJQzxHa8tqmBTERoUE0Eh1gSBASVRYNxU1V79cpaD9LNj3dmOugy16Rkg9rr7mUsst57yT8npkUE+ebWS7lnnPLJnrtcqCwLCDFlDq0YWNrj0E/y0sO0M9fsLwEEHl+TwlcDplvGtudAsuRmme98PieP1jvAnoBKfCBj5ur2g7Sf+A5sHa8opo2RlVX3W4uEAmiM3I1IeB8rq+g6UQfgsvika3VlgarRebwRFwg5U0OyfxTcvUHa0a8vQG9Of7gI+zHeTM9GNVloHn1HslEzgjhafHaVGpg+Ylz5nFXDeF76a7vhmYWIRladRw1eT8btUVdghvwo6Zj/H8pWZJwx9GKY=
